# Generated by Django 4.2 on 2023-04-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourserelation',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
