# Generated by Django 4.2 on 2023-04-18 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_studentcourserelation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourserelation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentcourserelation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
